#!/usr/bin/env python3
"""Generate paste-ready files for Sierra Interactive.

The source pages already hardcode every figure — there is no runtime data
dependency, no <script>, nothing fetched. What they are NOT is portable: 51
images are referenced with repo-relative paths like `../city-images/foo.jpg`,
which resolve locally and 404 the moment the markup is pasted into Sierra.

This rewrites those to absolute URLs and drops the editor-facing comment, so
each file in sierra-export/ can be pasted straight into TinyMCE's Source Code
view with nothing else to fix.

    python3 scripts/build_sierra.py
    python3 scripts/build_sierra.py --image-base https://cdn.example.com/img

Default host is jsDelivr serving this repo, which the pages already trust for
their icon set. Point --image-base at Sierra's own media library instead once
the images are uploaded there.
"""
import argparse
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "sierra-export"
DEFAULT_BASE = "https://cdn.jsdelivr.net/gh/jtcompass212/TheChenTeam@main"

# The "paste this into TinyMCE" banner is about the file, not the page; once
# you are in sierra-export/ it is noise. The MAP note is an instruction for
# what to do *after* pasting, so it stays.
PASTE_BANNER = re.compile(
    r'<!--\s*Paste everything below into TinyMCE.*?-->', re.S)

# Repo-relative sources sit at different depths: city pages reach up one level
# (`../city-images/...`), neighborhood pages two (`../../neighborhood-images/...`).
# Strip every leading `../` so the path is repo-root-relative before prefixing,
# otherwise the base URL gets a `/../` glued into it and the image 404s.
REL_SRC = re.compile(r'src="((?:\.\./)+)([^"]+)"')


def convert(html, base):
    html = PASTE_BANNER.sub("", html, count=1).lstrip("\n")
    html, n = REL_SRC.subn(lambda m: f'src="{base}/{m.group(2)}"', html)
    return html, n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--image-base", default=DEFAULT_BASE,
                    help="absolute URL prefix the images are served from")
    ap.add_argument("--check", action="store_true",
                    help="verify only; do not write")
    args = ap.parse_args()
    base = args.image_base.rstrip("/")

    sources = ([(p, p.stem + ".html") for p in sorted((ROOT / "city-pages").glob("*.html"))]
               + [(p, f"{p.parent.name}/{p.name}")
                  for p in sorted((ROOT / "neighborhood-pages").glob("*/*.html"))])

    if not args.check and OUT.exists():
        shutil.rmtree(OUT)

    rewritten, problems = 0, []
    for src, rel in sources:
        html, n = convert(src.read_text(), base)
        rewritten += n

        # Nothing may reference the filesystem after conversion.
        for stray in re.findall(r'(?:src|href)="(?!https?://|#|/)([^"]+)"', html):
            if not stray.startswith(("mailto:", "tel:")):
                problems.append(f"{rel}: unresolved path {stray!r}")
        # An absolute URL with a `/../` in it is still broken — it just looks fine.
        for mangled in re.findall(r'(?:src|href)="(https?://[^"]*/\.\./[^"]*)"', html):
            problems.append(f"{rel}: traversal left in URL {mangled!r}")
        # Every rewritten image must point at a file that actually exists.
        for url in re.findall(rf'src="{re.escape(base)}/([^"]+)"', html):
            if not (ROOT / url).exists():
                problems.append(f"{rel}: image not in repo {url!r}")

        if not args.check:
            dest = OUT / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(html)

    if not args.check:
        (OUT / "README.md").write_text(f"""# Sierra Interactive — paste-ready pages

Generated by `scripts/build_sierra.py`. **Do not edit these by hand** — they
are overwritten on every build. Edit the source pages in `city-pages/` and
`neighborhood-pages/`, then re-run the script.

## Pasting a page

1. Open the page in Sierra, add a **Content Area** component.
2. Open TinyMCE's Source Code view — the `<>` icon in the toolbar. Paste into
   that, not the WYSIWYG pane.
3. Paste the whole file.

Neighborhood pages carry a comment noting that the interactive map is a
**separate Shared HTML Widget**, added as a new page component positioned
after the Content Area block.

## Images

Every image is an absolute URL under `{base}`,
so nothing depends on the repo being checked out. If you upload the images to
Sierra's media library instead, rebuild pointing at it:

    python3 scripts/build_sierra.py --image-base https://your-sierra-media-url

## Contents

- {len([s for s in sources if '/' not in s[1]])} city pages
- {len([s for s in sources if '/' in s[1]])} neighborhood pages
""")

    print(f"image base: {base}")
    print(f"{'checked' if args.check else 'wrote'} {len(sources)} files, "
          f"{rewritten} image paths made absolute")
    if problems:
        print(f"\n{len(problems)} unresolved reference(s):")
        for p in problems:
            print("  " + p)
        return 1
    print("no unresolved local references")
    return 0


if __name__ == "__main__":
    sys.exit(main())
